#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="upload")]
	public partial class uploadLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertupload(upload instance);
    partial void Updateupload(upload instance);
    partial void Deleteupload(upload instance);
    #endregion
		
		public uploadLinqDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["uploadConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public uploadLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public uploadLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public uploadLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public uploadLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<upload> uploads
		{
			get
			{
				return this.GetTable<upload>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.upload")]
	public partial class upload : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _name;
		
		private string _filesource;
		
		private string _tag1;
		
		private string _tag2;
		
		private string _tag3;
		
		private int _SId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnfilesourceChanging(string value);
    partial void OnfilesourceChanged();
    partial void Ontag1Changing(string value);
    partial void Ontag1Changed();
    partial void Ontag2Changing(string value);
    partial void Ontag2Changed();
    partial void Ontag3Changing(string value);
    partial void Ontag3Changed();
    partial void OnSIdChanging(int value);
    partial void OnSIdChanged();
    #endregion
		
		public upload()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filesource", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string filesource
		{
			get
			{
				return this._filesource;
			}
			set
			{
				if ((this._filesource != value))
				{
					this.OnfilesourceChanging(value);
					this.SendPropertyChanging();
					this._filesource = value;
					this.SendPropertyChanged("filesource");
					this.OnfilesourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag1", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string tag1
		{
			get
			{
				return this._tag1;
			}
			set
			{
				if ((this._tag1 != value))
				{
					this.Ontag1Changing(value);
					this.SendPropertyChanging();
					this._tag1 = value;
					this.SendPropertyChanged("tag1");
					this.Ontag1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag2", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string tag2
		{
			get
			{
				return this._tag2;
			}
			set
			{
				if ((this._tag2 != value))
				{
					this.Ontag2Changing(value);
					this.SendPropertyChanging();
					this._tag2 = value;
					this.SendPropertyChanged("tag2");
					this.Ontag2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag3", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string tag3
		{
			get
			{
				return this._tag3;
			}
			set
			{
				if ((this._tag3 != value))
				{
					this.Ontag3Changing(value);
					this.SendPropertyChanging();
					this._tag3 = value;
					this.SendPropertyChanged("tag3");
					this.Ontag3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SId", DbType="Int NOT NULL")]
		public int SId
		{
			get
			{
				return this._SId;
			}
			set
			{
				if ((this._SId != value))
				{
					this.OnSIdChanging(value);
					this.SendPropertyChanging();
					this._SId = value;
					this.SendPropertyChanged("SId");
					this.OnSIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
