<?xml version="1.0" encoding="utf-8"?><Database Name="upload" Class="uploadLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\upload.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="uploadConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.upload" Member="uploads">
    <Type Name="upload">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="filesource" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="tag1" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="tag2" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="tag3" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="SId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>